<html>
  <head>
    <!-- 
      This page was generated by PHP Aptitude,
      Copyright 2009-2010 Artem Prilutskiy.
    -->
    <title>{$title}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" media="all" href="styles/{$target}.css"/>
  </head>
  <body>
    <h1>{$title}</h1>
    <table class="bordered">
      <tr>
        <td class="title">&nbsp;</td>
        <td class="title">Package</td>
        <td class="title">Version</td>
        <td class="title">Description</td>
        <td class="title">Author</td>
        <td class="title">Section</td>
        <td class="title">&nbsp;</td>
      </tr>
      {foreach key=name item=package from=$packages}
        <tr>
          <td class="center">
            {if isset($package.Maemo_Icon_26)}
              <img class="icon" src="icon.php?package={$name|escape:'url'}"/>
            {else}
              <img class="icon" src="package.png"/>
            {/if}
          </td>
          <td>
            {if isset($package.Maemo_Display_Name)}
              {$package.Maemo_Display_Name}
            {else}
              {$name}
            {/if}
          </td>
          <td>{$package.Version}</td>
          <td>{$package.Description|escape|nl2br|@make_hyperlink}</td>
          <td>{$package.Maintainer|@hide_mail|escape}</td>
          <td>{$package.Section|@get_section|ucwords}</td>
          <td class="center">
            <a href="../install.php?package={$name|escape:'url'}">Install</a>
            &nbsp;
            <a href="log.php?package={$name|escape:'url'}">ChangeLog</a>
          </td>
        </tr>
      {/foreach}
    </table>
  </body>
</html>
