<html>
  <head>
    <!--
      This page was generated by PHP Aptitude,
      Copyright 2009-2010 Artem Prilutskiy.
    -->
    <title>{$title}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" media="all" href="styles/{$target}.css"/>
  </head>
  <body>
    <h1>
      {if isset($package.Maemo_Display_Name)}
        {$package.Maemo_Display_Name}
      {else}
        {$name}
      {/if}
      {$package.Version} - ChangeLog
    </h1>
    <div class="code">
      {$output|escape|nl2br|@make_hyperlink}
    </div>
  </body>
</html>
